### ISSUE TITLE
Tests segregation

### ISSUE THREAD

**Issue by owulveryck** [owulveryck/gorgonnx#9]
The integration tests (issued from ONNX) are melted with the unit tests.

Thanks to the tool for code generation, I think they should be isolated from the `gorgonnx` package and generated thanks to a `// go generate` comment.

This would allow a better maintainability of the repository and would ease the addition and tests of new operators.

Any opinion @blackrez ?

**Comment by blackrez** [comment]
It's a good idea to isolated generated tests and unit tests.

Should the command download data tests from onnx project and then generate tests?

**Comment by owulveryck** [comment]
Maybe it should... and it would ease the decision about the licence you mentioned in [issue 11](https://github.com/owulveryck/gorgonnx/issues/11)
